[workspace]
members = [
    "casper_ido",
    "testing/tests",
    "testing/erc20-test-call",
]
default-members = [
    "casper_ido",
    "testing/tests",
    "testing/erc20-test-call",
]

[profile.release]
codegen-units = 1
lto = true
